version: "3"
services:
  server:
    #build:
    #context: .
    #dockerfile: prod.dockerfile
    image: easyticket01/easyticketback
    ports:
      - 4000:4000
    command: sh -c "yarn run"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src/
      - ./ormconfig.json:/app/ormconfig.json
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: easyPass
      MYSQL_DATABASE: easyTicket
    volumes:
      - easyTicketDb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  easyTicketDb:
  web-client-build:


