version: "3"
services:
  server:
    #build:
    #context: .
    #dockerfile: prod.dockerfile
    image: easyticket01/easyticketback
    ports:
      - 4000:4000
    command: sh -c "yarn run"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: easyPass
      MYSQL_DATABASE: easyTicket
    volumes:
      - easyTicketDb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  easyTicketDb:


