version: "3"
services:
  server:
    #build:
    #context: .
    #dockerfile: dev.dockerfile
    image: easyticket01/easyticketback
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src/
      - ./ormconfig.json:/app/ormconfig.json
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: easyPass
      MYSQL_DATABASE: easyTest
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      retries: 10
