version: "3"
services:
  server:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src/
      - ./ormconfig.json:/app/ormconfig.json
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: easyPass
      MYSQL_DATABASE: easyTicket
    volumes:
      - easyTicketDb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  easyTicketDb:
