name: push-procedure

on:
  push:
    branches:
      - "*"

jobs:
  push-procedure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Check lint
        run: yarn run eslint
      - name: Run tests
        run: npm run test
