name: push-procedure

on:
  push:
    branches:
      - "*"

jobs:
  push-procedure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Check lint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run tests
        run: npm run test
